### PR TITLE
Fix #1 and #2, #3 Add template functionality for branch coverage + scripts

### LINKED ISSUE #1: Create branch coverage template functionality
Create a template for branch coverage that can be added to all functions that are to be examined.

### PR DESCRIPTION
**Pull request by sashahe**
Add template functionality to track branch path for execution of each test. 

1. Find ID of your function [here](https://docs.google.com/document/d/17DiYgBpSQGz-z66rJ12hcXo3eFWngok13n1FrMnJ800/edit?usp=sharing).
2. Calculate the number of branches in your function and change the value of `numberOfBranches`.
3. Add `branches[x] = 1` in all places that define a new branch.
4. Edith the file name to the correct ID.
5. Repeat these steps for both of your functions and then approve this PR (if you agree with it :+1:)

Why are we doing this?
When we run gradle build, the test will execute. This will in turn generate a result vector that represents the path that the test took. We can then use all the vectors combined that are found in the corresponding file to examine the total branch coveage. :smiling_imp: 

Fun fact, accidentally created a PR to the actual repo first... akward.

### CODE REVIEW

**Comment by sashahe** [comment]
This will break locally on your computer if you test it with `gradle build` because the empty directory `branchtest` was not added to the commit. Ensure that you create this directory locally.

**Comment by sashahe** [comment]
Now there is a python script that can calculate and present the branch coverage for all tests if the correct naming convention is used when creating the result files.

**Review by gustafguner — APPROVED** [review]
Well done! I think this looks really good. 👍  I continued your work and implemented some additional stuff. The script now forces a re-run of the tests even though no file were changed. It also looks for all `.csv`-files instead of just one and it doesn't crash when it doesn't find one like it did before. I reformatted the output a bit too to make it more descriptive!

**Review by emetha — APPROVED** [review]
Works great! I just changed in the python to append instead of write so that the results for all functions are printed out as well as creates a result.txt file if it does not exists. The script now also removes any old result.txt file when it is run. Also added the branch coverage for functions with ID 2 and 3 to see if all the functions are printed out.

**Comment by sashahe** [comment]
Nice job @emetha @gustafguner! Im going to merge this now because we need to continue working :+1:

**Pull request merged**
