### PR TITLE
Fix #98 Add unit tests for getOrigin()

### LINKED ISSUE #98: Unit test getOrigin()
Create unit tests for getOrigin() located [here](https://github.com/gurkenlabs/litiengine/blob/master/src/de/gurkenlabs/litiengine/abilities/Ability.java).

See [REPORT.md](https://github.com/sashahe/litiengine/blob/issue/93/REPORT.md) for the requirements of the function.

### PR DESCRIPTION
**Pull request by emetha**
See issue #98 for more information.

### CODE REVIEW

**Review by sashahe — APPROVED** [review]
Looks good to me :+1:

**Review by sashahe — CHANGES_REQUESTED** [review]
I just remembered the feedback we got on the first assignment about our unit tests. They suggested that each case should be a separate test so that it is easier to run the test and see what fails :) I think we should divide the tests up like this!

**Comment by emetha** [comment]
Ok! Im on it :)

**Review by sashahe — APPROVED** [review]
Looks good!

**Pull request merged**
